import type { Locale } from "../i18n/routing";

type Messages = Record<string, string>;

const en: Messages = {
  "studio.workbench.settings": "Settings", "studio.workbench.modelOutput": "Model and output", "studio.workbench.preview": "Preview", "studio.workbench.example": "Example",
  "studio.workbench.avatarExampleNote": "This example is shown only for Kling Avatar models. Your generated result will appear in Projects.", "studio.workbench.openPreview": "Open preview", "studio.workbench.openProjects": "Open projects",
  "studio.workbench.previous": "Previous", "studio.workbench.next": "Next", "studio.workbench.fullscreen": "Fullscreen", "studio.workbench.recent": "Recent Generations", "studio.workbench.latest": "Your latest AI creations", "studio.workbench.allProjects": "All projects",
  "studio.workbench.sampleVideo": "Sample video", "studio.workbench.videoPreview": "Video preview", "studio.workbench.characters": "{count} characters", "studio.workbench.promptDetail": "Describe your idea in detail...", "studio.workbench.presets": "Presets",
  "studio.workbench.moreSettings": "More settings", "studio.workbench.lessSettings": "Less settings", "studio.workbench.advancedSettings": "Advanced Settings", "studio.workbench.hideAdvancedSettings": "Hide Advanced Settings", "studio.workbench.exploreModels": "Explore the best model for your idea", "studio.workbench.enhancePrompt": "Enhance prompt", "studio.workbench.inspire": "Inspire me",
  "studio.workbench.preset.cinematic": "Cinematic", "studio.workbench.preset.product": "Product promo", "studio.workbench.preset.lifestyle": "Lifestyle vlog", "studio.workbench.preset.cyberpunk": "Cyberpunk", "studio.workbench.preset.minimal": "Minimal",
  "studio.workbench.navStudio": "Studio", "studio.workbench.navAssets": "Assets", "studio.workbench.collapse": "Collapse", "studio.workbench.guest": "Guest", "studio.workbench.user": "DreamFace User",
  "studio.modelPicker.title": "Choose an AI model", "studio.modelPicker.subtitle": "Compare speed and estimated credit cost.", "studio.modelPicker.close": "Close model picker", "studio.modelPicker.search": "Search models", "studio.modelPicker.selected": "Selected", "studio.modelPicker.noMatches": "No matching models",
  "studio.modelPicker.label": "AI model", "studio.modelPicker.available": "{count} available", "studio.modelPicker.onlyAvailable": "Only option", "studio.modelPicker.change": "Change", "studio.modelPicker.estimatedCredits": "~{credits} credits",
  "studio.modelPicker.group.recommended": "Recommended", "studio.modelPicker.group.fast": "Fast & everyday", "studio.modelPicker.group.better": "Better quality", "studio.modelPicker.group.premium": "Premium quality", "studio.modelPicker.group.highQuality": "Higher quality", "studio.modelPicker.group.efficient": "Fast & efficient", "studio.modelPicker.group.editing": "Editing & efficiency", "studio.modelPicker.group.avatar": "Avatar models", "studio.modelPicker.group.premiumAvatar": "Premium avatar", "studio.modelPicker.group.available": "Available model",
  "studio.modelPicker.speed.fastest": "Fastest", "studio.modelPicker.speed.fast": "Fast", "studio.modelPicker.speed.balanced": "Balanced", "studio.modelPicker.speed.medium": "Medium", "studio.modelPicker.speed.slower": "Slower", "studio.modelPicker.speed.standard": "Standard"
};

const zhCN: Messages = { ...en,
  "studio.workbench.advancedSettings": "\u9ad8\u7ea7\u8bbe\u7f6e", "studio.workbench.hideAdvancedSettings": "\u6536\u8d77\u9ad8\u7ea7\u8bbe\u7f6e",
  "studio.workbench.settings": "设置", "studio.workbench.modelOutput": "模型与输出", "studio.workbench.preview": "预览", "studio.workbench.example": "示例", "studio.workbench.avatarExampleNote": "此示例仅适用于 Kling Avatar 模型。生成结果会显示在项目中。", "studio.workbench.openPreview": "打开预览", "studio.workbench.openProjects": "打开项目", "studio.workbench.previous": "上一个", "studio.workbench.next": "下一个", "studio.workbench.fullscreen": "全屏", "studio.workbench.recent": "最近生成", "studio.workbench.latest": "你最近的 AI 创作", "studio.workbench.allProjects": "全部项目", "studio.workbench.sampleVideo": "示例视频", "studio.workbench.videoPreview": "视频预览", "studio.workbench.characters": "{count} 个字符", "studio.workbench.promptDetail": "详细描述你的想法…", "studio.workbench.presets": "预设", "studio.workbench.moreSettings": "更多设置", "studio.workbench.lessSettings": "收起设置", "studio.workbench.exploreModels": "为你的创意选择更合适的模型", "studio.workbench.enhancePrompt": "增强提示词", "studio.workbench.inspire": "给我灵感", "studio.workbench.preset.cinematic": "电影感", "studio.workbench.preset.product": "产品宣传", "studio.workbench.preset.lifestyle": "生活记录", "studio.workbench.preset.cyberpunk": "赛博朋克", "studio.workbench.preset.minimal": "极简", "studio.workbench.navStudio": "工作台", "studio.workbench.navAssets": "素材", "studio.workbench.collapse": "收起", "studio.workbench.guest": "访客", "studio.workbench.user": "DreamFace 用户",
  "studio.modelPicker.title": "选择 AI 模型", "studio.modelPicker.subtitle": "比较生成速度和预计积分。", "studio.modelPicker.close": "关闭模型选择", "studio.modelPicker.search": "搜索模型", "studio.modelPicker.selected": "已选择", "studio.modelPicker.noMatches": "没有匹配的模型", "studio.modelPicker.label": "AI 模型", "studio.modelPicker.available": "可选 {count} 个", "studio.modelPicker.onlyAvailable": "唯一可用", "studio.modelPicker.change": "更换", "studio.modelPicker.estimatedCredits": "约 {credits} 积分", "studio.modelPicker.group.recommended": "推荐", "studio.modelPicker.group.fast": "快速日常", "studio.modelPicker.group.better": "更高质量", "studio.modelPicker.group.premium": "顶级质量", "studio.modelPicker.group.highQuality": "高质量", "studio.modelPicker.group.efficient": "快速高效", "studio.modelPicker.group.editing": "编辑与效率", "studio.modelPicker.group.avatar": "数字人模型", "studio.modelPicker.group.premiumAvatar": "高级数字人", "studio.modelPicker.group.available": "可用模型", "studio.modelPicker.speed.fastest": "最快", "studio.modelPicker.speed.fast": "快速", "studio.modelPicker.speed.balanced": "均衡", "studio.modelPicker.speed.medium": "中等", "studio.modelPicker.speed.slower": "较慢", "studio.modelPicker.speed.standard": "标准"
};

const translated = (overrides: Messages): Messages => ({ ...en, ...overrides });

const rtlArabic: Messages = {
  "studio.workbench.settings": "الإعدادات", "studio.workbench.modelOutput": "النموذج والمخرجات", "studio.workbench.preview": "معاينة", "studio.workbench.example": "مثال", "studio.workbench.avatarExampleNote": "يظهر هذا المثال لنماذج Kling Avatar فقط. ستظهر النتيجة في المشاريع.", "studio.workbench.openPreview": "فتح المعاينة", "studio.workbench.openProjects": "فتح المشاريع", "studio.workbench.previous": "السابق", "studio.workbench.next": "التالي", "studio.workbench.fullscreen": "ملء الشاشة", "studio.workbench.recent": "الإنشاءات الأخيرة", "studio.workbench.latest": "أحدث إبداعاتك بالذكاء الاصطناعي", "studio.workbench.allProjects": "كل المشاريع", "studio.workbench.sampleVideo": "فيديو تجريبي", "studio.workbench.videoPreview": "معاينة الفيديو", "studio.workbench.characters": "{count} حرفًا", "studio.workbench.promptDetail": "صِف فكرتك بالتفصيل…", "studio.workbench.presets": "أنماط جاهزة", "studio.workbench.moreSettings": "إعدادات إضافية", "studio.workbench.lessSettings": "إخفاء الإعدادات", "studio.workbench.exploreModels": "اختر أفضل نموذج لفكرتك", "studio.workbench.enhancePrompt": "تحسين الوصف", "studio.workbench.inspire": "ألهمني", "studio.workbench.preset.cinematic": "سينمائي", "studio.workbench.preset.product": "إعلان منتج", "studio.workbench.preset.lifestyle": "نمط حياة", "studio.workbench.preset.cyberpunk": "سايبربانك", "studio.workbench.preset.minimal": "بسيط", "studio.workbench.navStudio": "الاستوديو", "studio.workbench.navAssets": "الأصول", "studio.workbench.collapse": "طي", "studio.workbench.guest": "زائر", "studio.workbench.user": "مستخدم DreamFace",
  "studio.modelPicker.group.recommended": "موصى به", "studio.modelPicker.group.fast": "سريع ويومي", "studio.modelPicker.group.better": "جودة أفضل", "studio.modelPicker.group.premium": "جودة ممتازة", "studio.modelPicker.group.highQuality": "جودة عالية", "studio.modelPicker.group.efficient": "سريع وفعّال", "studio.modelPicker.group.editing": "تحرير وكفاءة", "studio.modelPicker.group.avatar": "نماذج الصور الرمزية", "studio.modelPicker.group.premiumAvatar": "صورة رمزية ممتازة", "studio.modelPicker.group.available": "نموذج متاح", "studio.modelPicker.speed.fastest": "الأسرع", "studio.modelPicker.speed.fast": "سريع", "studio.modelPicker.speed.balanced": "متوازن", "studio.modelPicker.speed.medium": "متوسط", "studio.modelPicker.speed.slower": "أبطأ", "studio.modelPicker.speed.standard": "قياسي"
};

const rtlHebrew: Messages = {
  "studio.workbench.settings": "הגדרות", "studio.workbench.modelOutput": "מודל ופלט", "studio.workbench.preview": "תצוגה מקדימה", "studio.workbench.example": "דוגמה", "studio.workbench.avatarExampleNote": "דוגמה זו מוצגת רק למודלי Kling Avatar. התוצאה תופיע בפרויקטים.", "studio.workbench.openPreview": "פתיחת תצוגה", "studio.workbench.openProjects": "פתיחת פרויקטים", "studio.workbench.previous": "הקודם", "studio.workbench.next": "הבא", "studio.workbench.fullscreen": "מסך מלא", "studio.workbench.recent": "יצירות אחרונות", "studio.workbench.latest": "יצירות ה-AI האחרונות שלך", "studio.workbench.allProjects": "כל הפרויקטים", "studio.workbench.sampleVideo": "וידאו לדוגמה", "studio.workbench.videoPreview": "תצוגת וידאו", "studio.workbench.characters": "{count} תווים", "studio.workbench.promptDetail": "תארו את הרעיון בפירוט…", "studio.workbench.presets": "סגנונות מוכנים", "studio.workbench.moreSettings": "הגדרות נוספות", "studio.workbench.lessSettings": "פחות הגדרות", "studio.workbench.exploreModels": "בחרו את המודל המתאים לרעיון", "studio.workbench.enhancePrompt": "שיפור ההנחיה", "studio.workbench.inspire": "תנו לי השראה", "studio.workbench.preset.cinematic": "קולנועי", "studio.workbench.preset.product": "קידום מוצר", "studio.workbench.preset.lifestyle": "סגנון חיים", "studio.workbench.preset.cyberpunk": "סייברפאנק", "studio.workbench.preset.minimal": "מינימלי", "studio.workbench.navStudio": "סטודיו", "studio.workbench.navAssets": "נכסים", "studio.workbench.collapse": "כווץ", "studio.workbench.guest": "אורח", "studio.workbench.user": "משתמש DreamFace",
  "studio.modelPicker.group.recommended": "מומלץ", "studio.modelPicker.group.fast": "מהיר ויומיומי", "studio.modelPicker.group.better": "איכות טובה יותר", "studio.modelPicker.group.premium": "איכות פרימיום", "studio.modelPicker.group.highQuality": "איכות גבוהה", "studio.modelPicker.group.efficient": "מהיר ויעיל", "studio.modelPicker.group.editing": "עריכה ויעילות", "studio.modelPicker.group.avatar": "מודלי אווטאר", "studio.modelPicker.group.premiumAvatar": "אווטאר פרימיום", "studio.modelPicker.group.available": "מודל זמין", "studio.modelPicker.speed.fastest": "המהיר ביותר", "studio.modelPicker.speed.fast": "מהיר", "studio.modelPicker.speed.balanced": "מאוזן", "studio.modelPicker.speed.medium": "בינוני", "studio.modelPicker.speed.slower": "איטי יותר", "studio.modelPicker.speed.standard": "רגיל"
};

export const studioWorkbenchUiMessages: Partial<Record<Locale, Messages>> = {
  en, "zh-CN": zhCN,
  "zh-TW": translated({ ...zhCN, "studio.workbench.settings": "設定", "studio.workbench.modelOutput": "模型與輸出", "studio.workbench.openProjects": "開啟專案", "studio.workbench.characters": "{count} 個字元", "studio.workbench.promptDetail": "詳細描述你的想法…", "studio.workbench.moreSettings": "更多設定", "studio.workbench.lessSettings": "收起設定", "studio.modelPicker.title": "選擇 AI 模型", "studio.modelPicker.subtitle": "比較生成速度和預估積分。", "studio.modelPicker.close": "關閉模型選擇", "studio.modelPicker.search": "搜尋模型", "studio.modelPicker.available": "可選 {count} 個", "studio.modelPicker.estimatedCredits": "約 {credits} 積分" }),
  de: translated({ "studio.workbench.settings": "Einstellungen", "studio.workbench.modelOutput": "Modell und Ausgabe", "studio.workbench.preview": "Vorschau", "studio.workbench.recent": "Letzte Generierungen", "studio.workbench.allProjects": "Alle Projekte", "studio.workbench.moreSettings": "Weitere Einstellungen", "studio.workbench.lessSettings": "Weniger Einstellungen", "studio.workbench.navAssets": "Medien", "studio.workbench.collapse": "Einklappen", "studio.modelPicker.title": "KI-Modell auswählen", "studio.modelPicker.subtitle": "Geschwindigkeit und geschätzte Credits vergleichen.", "studio.modelPicker.close": "Modellauswahl schließen", "studio.modelPicker.search": "Modelle suchen", "studio.modelPicker.selected": "Ausgewählt", "studio.modelPicker.noMatches": "Keine passenden Modelle", "studio.modelPicker.label": "KI-Modell", "studio.modelPicker.available": "{count} verfügbar", "studio.modelPicker.onlyAvailable": "Einzige Option", "studio.modelPicker.change": "Ändern", "studio.modelPicker.estimatedCredits": "~{credits} Credits" }),
  fr: translated({ "studio.workbench.settings": "Paramètres", "studio.workbench.modelOutput": "Modèle et sortie", "studio.workbench.preview": "Aperçu", "studio.workbench.recent": "Générations récentes", "studio.workbench.allProjects": "Tous les projets", "studio.workbench.moreSettings": "Plus de paramètres", "studio.workbench.lessSettings": "Moins de paramètres", "studio.workbench.navAssets": "Ressources", "studio.workbench.collapse": "Réduire", "studio.modelPicker.title": "Choisir un modèle d’IA", "studio.modelPicker.subtitle": "Comparez la vitesse et le coût estimé.", "studio.modelPicker.close": "Fermer le sélecteur", "studio.modelPicker.search": "Rechercher des modèles", "studio.modelPicker.selected": "Sélectionné", "studio.modelPicker.noMatches": "Aucun modèle correspondant", "studio.modelPicker.label": "Modèle d’IA", "studio.modelPicker.available": "{count} disponibles", "studio.modelPicker.onlyAvailable": "Seule option", "studio.modelPicker.change": "Changer", "studio.modelPicker.estimatedCredits": "~{credits} crédits" }),
  es: translated({ "studio.workbench.settings": "Ajustes", "studio.workbench.modelOutput": "Modelo y salida", "studio.workbench.preview": "Vista previa", "studio.workbench.recent": "Generaciones recientes", "studio.workbench.allProjects": "Todos los proyectos", "studio.workbench.moreSettings": "Más ajustes", "studio.workbench.lessSettings": "Menos ajustes", "studio.workbench.navAssets": "Recursos", "studio.workbench.collapse": "Contraer", "studio.modelPicker.title": "Elegir modelo de IA", "studio.modelPicker.subtitle": "Compara velocidad y créditos estimados.", "studio.modelPicker.close": "Cerrar selector", "studio.modelPicker.search": "Buscar modelos", "studio.modelPicker.selected": "Seleccionado", "studio.modelPicker.noMatches": "No hay modelos coincidentes", "studio.modelPicker.label": "Modelo de IA", "studio.modelPicker.available": "{count} disponibles", "studio.modelPicker.onlyAvailable": "Única opción", "studio.modelPicker.change": "Cambiar", "studio.modelPicker.estimatedCredits": "~{credits} créditos" }),
  it: translated({ "studio.workbench.settings": "Impostazioni", "studio.workbench.modelOutput": "Modello e output", "studio.workbench.preview": "Anteprima", "studio.workbench.recent": "Generazioni recenti", "studio.workbench.allProjects": "Tutti i progetti", "studio.workbench.moreSettings": "Altre impostazioni", "studio.workbench.lessSettings": "Meno impostazioni", "studio.workbench.navAssets": "Risorse", "studio.workbench.collapse": "Comprimi", "studio.modelPicker.title": "Scegli un modello IA", "studio.modelPicker.subtitle": "Confronta velocità e crediti stimati.", "studio.modelPicker.close": "Chiudi selettore", "studio.modelPicker.search": "Cerca modelli", "studio.modelPicker.selected": "Selezionato", "studio.modelPicker.noMatches": "Nessun modello corrispondente", "studio.modelPicker.label": "Modello IA", "studio.modelPicker.available": "{count} disponibili", "studio.modelPicker.onlyAvailable": "Unica opzione", "studio.modelPicker.change": "Cambia", "studio.modelPicker.estimatedCredits": "~{credits} crediti" }),
  "pt-BR": translated({ "studio.workbench.settings": "Configurações", "studio.workbench.modelOutput": "Modelo e saída", "studio.workbench.preview": "Prévia", "studio.workbench.recent": "Gerações recentes", "studio.workbench.allProjects": "Todos os projetos", "studio.workbench.moreSettings": "Mais configurações", "studio.workbench.lessSettings": "Menos configurações", "studio.workbench.navAssets": "Recursos", "studio.workbench.collapse": "Recolher", "studio.modelPicker.title": "Escolher modelo de IA", "studio.modelPicker.subtitle": "Compare velocidade e créditos estimados.", "studio.modelPicker.close": "Fechar seletor", "studio.modelPicker.search": "Buscar modelos", "studio.modelPicker.selected": "Selecionado", "studio.modelPicker.noMatches": "Nenhum modelo encontrado", "studio.modelPicker.label": "Modelo de IA", "studio.modelPicker.available": "{count} disponíveis", "studio.modelPicker.onlyAvailable": "Única opção", "studio.modelPicker.change": "Alterar", "studio.modelPicker.estimatedCredits": "~{credits} créditos" }),
  ru: translated({ "studio.workbench.settings": "Настройки", "studio.workbench.modelOutput": "Модель и результат", "studio.workbench.preview": "Предпросмотр", "studio.workbench.recent": "Недавние генерации", "studio.workbench.allProjects": "Все проекты", "studio.workbench.moreSettings": "Больше настроек", "studio.workbench.lessSettings": "Скрыть настройки", "studio.workbench.navAssets": "Материалы", "studio.workbench.collapse": "Свернуть", "studio.modelPicker.title": "Выберите модель ИИ", "studio.modelPicker.subtitle": "Сравните скорость и примерную стоимость.", "studio.modelPicker.close": "Закрыть выбор модели", "studio.modelPicker.search": "Поиск моделей", "studio.modelPicker.selected": "Выбрано", "studio.modelPicker.noMatches": "Подходящих моделей нет", "studio.modelPicker.label": "Модель ИИ", "studio.modelPicker.available": "Доступно: {count}", "studio.modelPicker.onlyAvailable": "Единственный вариант", "studio.modelPicker.change": "Изменить", "studio.modelPicker.estimatedCredits": "~{credits} кредитов" }),
  vi: translated({ "studio.workbench.settings": "Cài đặt", "studio.workbench.modelOutput": "Model và đầu ra", "studio.workbench.preview": "Xem trước", "studio.workbench.recent": "Nội dung gần đây", "studio.workbench.allProjects": "Tất cả dự án", "studio.workbench.moreSettings": "Thêm cài đặt", "studio.workbench.lessSettings": "Thu gọn cài đặt", "studio.workbench.navAssets": "Tài nguyên", "studio.workbench.collapse": "Thu gọn", "studio.modelPicker.title": "Chọn model AI", "studio.modelPicker.subtitle": "So sánh tốc độ và credit ước tính.", "studio.modelPicker.close": "Đóng chọn model", "studio.modelPicker.search": "Tìm model", "studio.modelPicker.selected": "Đã chọn", "studio.modelPicker.noMatches": "Không có model phù hợp", "studio.modelPicker.label": "Model AI", "studio.modelPicker.available": "{count} lựa chọn", "studio.modelPicker.onlyAvailable": "Lựa chọn duy nhất", "studio.modelPicker.change": "Đổi", "studio.modelPicker.estimatedCredits": "~{credits} credit" }),
  ja: translated({ "studio.workbench.settings": "設定", "studio.workbench.modelOutput": "モデルと出力", "studio.workbench.preview": "プレビュー", "studio.workbench.recent": "最近の生成", "studio.workbench.allProjects": "すべてのプロジェクト", "studio.workbench.moreSettings": "その他の設定", "studio.workbench.lessSettings": "設定を閉じる", "studio.workbench.navAssets": "素材", "studio.workbench.collapse": "折りたたむ", "studio.modelPicker.title": "AIモデルを選択", "studio.modelPicker.subtitle": "速度と推定クレジットを比較します。", "studio.modelPicker.close": "モデル選択を閉じる", "studio.modelPicker.search": "モデルを検索", "studio.modelPicker.selected": "選択中", "studio.modelPicker.noMatches": "一致するモデルはありません", "studio.modelPicker.label": "AIモデル", "studio.modelPicker.available": "{count}件利用可能", "studio.modelPicker.onlyAvailable": "唯一の選択肢", "studio.modelPicker.change": "変更", "studio.modelPicker.estimatedCredits": "約{credits}クレジット" }),
  ko: translated({ "studio.workbench.settings": "설정", "studio.workbench.modelOutput": "모델 및 출력", "studio.workbench.preview": "미리보기", "studio.workbench.recent": "최근 생성", "studio.workbench.allProjects": "모든 프로젝트", "studio.workbench.moreSettings": "추가 설정", "studio.workbench.lessSettings": "설정 접기", "studio.workbench.navAssets": "에셋", "studio.workbench.collapse": "접기", "studio.modelPicker.title": "AI 모델 선택", "studio.modelPicker.subtitle": "속도와 예상 크레딧을 비교하세요.", "studio.modelPicker.close": "모델 선택 닫기", "studio.modelPicker.search": "모델 검색", "studio.modelPicker.selected": "선택됨", "studio.modelPicker.noMatches": "일치하는 모델 없음", "studio.modelPicker.label": "AI 모델", "studio.modelPicker.available": "{count}개 사용 가능", "studio.modelPicker.onlyAvailable": "유일한 옵션", "studio.modelPicker.change": "변경", "studio.modelPicker.estimatedCredits": "약 {credits} 크레딧" }),
  th: translated({ "studio.workbench.settings": "การตั้งค่า", "studio.workbench.modelOutput": "โมเดลและผลลัพธ์", "studio.workbench.preview": "ตัวอย่าง", "studio.workbench.recent": "ผลงานล่าสุด", "studio.workbench.allProjects": "ทุกโปรเจกต์", "studio.workbench.moreSettings": "การตั้งค่าเพิ่มเติม", "studio.workbench.lessSettings": "ซ่อนการตั้งค่า", "studio.workbench.navAssets": "สื่อ", "studio.workbench.collapse": "ย่อ", "studio.modelPicker.title": "เลือกโมเดล AI", "studio.modelPicker.subtitle": "เปรียบเทียบความเร็วและเครดิตโดยประมาณ", "studio.modelPicker.close": "ปิดตัวเลือกโมเดล", "studio.modelPicker.search": "ค้นหาโมเดล", "studio.modelPicker.selected": "เลือกแล้ว", "studio.modelPicker.noMatches": "ไม่พบโมเดล", "studio.modelPicker.label": "โมเดล AI", "studio.modelPicker.available": "มี {count} ตัวเลือก", "studio.modelPicker.onlyAvailable": "ตัวเลือกเดียว", "studio.modelPicker.change": "เปลี่ยน", "studio.modelPicker.estimatedCredits": "~{credits} เครดิต" }),
  nl: translated({ "studio.workbench.settings": "Instellingen", "studio.workbench.modelOutput": "Model en uitvoer", "studio.workbench.preview": "Voorbeeld", "studio.workbench.recent": "Recente generaties", "studio.workbench.allProjects": "Alle projecten", "studio.workbench.moreSettings": "Meer instellingen", "studio.workbench.lessSettings": "Minder instellingen", "studio.workbench.navAssets": "Assets", "studio.workbench.collapse": "Inklappen", "studio.modelPicker.title": "AI-model kiezen", "studio.modelPicker.subtitle": "Vergelijk snelheid en geschatte credits.", "studio.modelPicker.close": "Modelkiezer sluiten", "studio.modelPicker.search": "Modellen zoeken", "studio.modelPicker.selected": "Geselecteerd", "studio.modelPicker.noMatches": "Geen passende modellen", "studio.modelPicker.label": "AI-model", "studio.modelPicker.available": "{count} beschikbaar", "studio.modelPicker.onlyAvailable": "Enige optie", "studio.modelPicker.change": "Wijzigen", "studio.modelPicker.estimatedCredits": "~{credits} credits" }),
  he: translated({ ...rtlHebrew, "studio.modelPicker.title": "בחירת מודל AI", "studio.modelPicker.subtitle": "השוואת מהירות ועלות משוערת.", "studio.modelPicker.close": "סגירת בחירת מודל", "studio.modelPicker.search": "חיפוש מודלים", "studio.modelPicker.selected": "נבחר", "studio.modelPicker.noMatches": "לא נמצאו מודלים", "studio.modelPicker.label": "מודל AI", "studio.modelPicker.available": "{count} זמינים", "studio.modelPicker.onlyAvailable": "אפשרות יחידה", "studio.modelPicker.change": "שינוי", "studio.modelPicker.estimatedCredits": "~{credits} קרדיטים" }),
  ar: translated({ ...rtlArabic, "studio.modelPicker.title": "اختر نموذج الذكاء الاصطناعي", "studio.modelPicker.subtitle": "قارن السرعة والتكلفة المقدرة.", "studio.modelPicker.close": "إغلاق اختيار النموذج", "studio.modelPicker.search": "بحث عن نموذج", "studio.modelPicker.selected": "محدد", "studio.modelPicker.noMatches": "لا توجد نماذج مطابقة", "studio.modelPicker.label": "نموذج AI", "studio.modelPicker.available": "{count} متاحة", "studio.modelPicker.onlyAvailable": "الخيار الوحيد", "studio.modelPicker.change": "تغيير", "studio.modelPicker.estimatedCredits": "~{credits} رصيد" })
};
